export const LABELS = {
  common: {
    save: 'Guardar',
    saveChanges: 'Guardar cambios',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    done: 'Listo',
    back: '← Volver',
    optional: '(opcional)',
  },

  status: {
    pending: 'Pendiente',
    overdue: 'Vencido',
    paid: 'Pagado',
  },

  paymentMethod: {
    sinpe: 'SINPE',
    cash: 'Efectivo',
    transfer: 'Transferencia',
  },

  clients: {
    tab: 'Clientes',
    screenTitle: 'Clientes',
    newTitle: 'Nuevo cliente',
    editTitle: 'Editar cliente',
    deleteButton: 'Eliminar cliente',
    deleteAlertTitle: 'Eliminar cliente',
    deleteAlertMessage: (name: string) =>
      `¿Desactivar a ${name}? Sus cobros se conservarán.`,
    fieldName: 'Nombre',
    fieldPhone: 'Teléfono',
    fieldNotes: 'Notas',
    placeholderName: 'Ej: Ana Rodríguez',
    placeholderPhone: 'Ej: +506 8888-1234',
    placeholderNotes: 'Observaciones opcionales...',
    emptyTitle: 'Sin clientes',
    emptyHint: 'Usa el botón + para agregar uno',
    errorNameRequired: 'El nombre es obligatorio.',
  },

  charges: {
    sectionTitle: 'Cobros',
    newButton: '+ Nuevo cobro',
    newTitle: 'Nuevo cobro',
    emptyState: 'Sin cobros registrados',
    fieldConcept: 'Concepto',
    fieldAmount: 'Monto (₡)',
    fieldDueDate: 'Fecha de vencimiento',
    fieldClient: 'Cliente',
    placeholderConcept: 'Ej: Mensualidad mayo',
    placeholderAmount: 'Ej: 35000',
    placeholderDueDate: 'Seleccionar fecha',
    useTemplate: 'Usar plantilla',
    duePrefix: 'Vence:',
    duePrefixShort: 'Vence',
    paidPrefix: 'Pagado el',
    tapToPayHint: 'Tocar para registrar pago →',
    revertButton: 'Revertir',
    revertAlertTitle: 'Revertir pago',
    revertAlertMessage:
      '¿Seguro? El cobro vuelve a pendiente y se borran los datos de pago.',
    errorConceptRequired: 'El concepto es obligatorio.',
    errorAmountInvalid: 'El monto debe ser un número mayor a 0.',
    errorDueDateRequired: 'La fecha de vencimiento es obligatoria.',
    resultSingular: 'resultado',
    resultPlural: 'resultados',
    chargeSingular: 'cobro',
    chargePlural: 'cobros',
    clearFilters: 'Quitar filtros',
    emptyFiltered: 'Sin cobros',
    emptyFilteredMessage: 'Ningún cobro coincide con los filtros',
    emptyInitialMessage: 'Aún no hay cobros registrados',
  },

  pay: {
    screenTitle: 'Registrar pago',
    chargeHeader: 'Cobro',
    fieldPaymentMethod: 'Método de pago',
    fieldPaymentDate: 'Fecha de pago',
    fieldNote: 'Nota',
    placeholderNote: 'Ej: Confirmado por WhatsApp',
    confirmButton: 'Confirmar pago',
    errorMethodRequired: 'Seleccioná el método de pago.',
  },

  templates: {
    tab: 'Plantillas',
    screenTitle: 'Plantillas',
    newTitle: 'Nueva plantilla',
    editTitle: 'Editar plantilla',
    deleteAlertTitle: 'Eliminar plantilla',
    deleteAlertMessage: (concept: string) =>
      `¿Eliminar "${concept}"? Los cobros existentes no se verán afectados.`,
    emptyTitle: 'Sin plantillas',
    emptyHint: 'Usa el botón + para agregar una',
    fieldConcept: 'Concepto',
    fieldAmount: 'Monto (₡)',
    placeholderConcept: 'Ej: Mensualidad mayo',
    placeholderAmount: 'Ej: 35000',
    errorConceptRequired: 'El concepto es obligatorio.',
    errorAmountInvalid: 'El monto debe ser un número mayor a 0.',
    pickerTitle: 'Elegir plantilla',
    pickerEmpty: 'No hay plantillas. Crea una desde la pestaña Plantillas.',
  },

  dashboard: {
    summaryTitle: 'Resumen',
    filterAll: 'Todos',
    filterClient: 'Cliente',
    rangePrevMonth: 'Mes ant.',
    rangeThisMonth: 'Este mes',
    rangeNextMonth: 'Próx. mes',
    allClients: 'Todos los clientes',
    searchClient: 'Buscar cliente…',
    filterModalTitle: 'Filtrar por cliente',
    totalReceivable: 'Por cobrar',
  },
} as const;
