export const LABELS = {
  common: {
    save: 'Guardar',
    saveChanges: 'Guardar cambios',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    done: 'Listo',
    back: '← Volver',
    optional: '(opcional)',
  },

  status: {
    pending: 'Pendiente',
    overdue: 'Vencido',
    paid: 'Pagado',
  },

  paymentMethod: {
    sinpe: 'SINPE',
    cash: 'Efectivo',
    transfer: 'Transferencia',
  },

  contacts: {
    tab: 'Contactos',
    screenTitle: 'Contactos',
    newTitle: 'Nuevo contacto',
    editTitle: 'Editar contacto',
    deleteButton: 'Eliminar contacto',
    deleteAlertTitle: 'Eliminar contacto',
    deleteAlertMessage: (name: string) =>
      `¿Desactivar a ${name}? Sus cobros se conservarán.`,
    fieldName: 'Nombre',
    fieldPhone: 'Teléfono',
    fieldEmail: 'Email',
    fieldMonthlyAmount: 'Mensualidad (₡)',
    fieldNotes: 'Notas',
    placeholderName: 'Ej: Ana Rodríguez',
    placeholderPhone: 'Ej: +506 8888-1234',
    placeholderEmail: 'Ej: correo@gmail.com',
    placeholderMonthlyAmount: 'Ej: 210000',
    placeholderNotes: 'Observaciones opcionales...',
    emptyTitle: 'Sin contactos',
    emptyHint: 'Usa el botón + para agregar uno',
    errorNameRequired: 'El nombre es obligatorio.',
  },

  charges: {
    sectionTitle: 'Cobros',
    newButton: '+ Nuevo cobro',
    newTitle: 'Nuevo cobro',
    emptyState: 'Sin cobros registrados',
    fieldConcept: 'Concepto',
    fieldAmount: 'Monto (₡)',
    fieldDueDate: 'Fecha de vencimiento',
    fieldContact: 'Contacto',
    fieldDescription: 'Descripción',
    fieldLineType: 'Tipo de línea',
    lineTypeRecurring: 'Recurrente',
    lineTypeExtra: 'Extra',
    placeholderConcept: 'Ej: Mensualidad mayo',
    placeholderAmount: 'Ej: 35000',
    placeholderDescription: 'Ej: Lucas + Clarita',
    placeholderDueDate: 'Seleccionar fecha',
    useTemplate: 'Usar plantilla',
    duePrefix: 'Vence:',
    duePrefixShort: 'Vence',
    paidPrefix: 'Pagado el',
    tapToPayHint: 'Tocar para registrar pago →',
    revertButton: 'Revertir',
    revertAlertTitle: 'Revertir pago',
    revertAlertMessage:
      '¿Seguro? El cobro vuelve a pendiente y se borran los datos de pago.',
    errorConceptRequired: 'El concepto es obligatorio.',
    errorAmountInvalid: 'El monto debe ser un número mayor a 0.',
    errorDueDateRequired: 'La fecha de vencimiento es obligatoria.',
    resultSingular: 'resultado',
    resultPlural: 'resultados',
    chargeSingular: 'cobro',
    chargePlural: 'cobros',
    clearFilters: 'Quitar filtros',
    emptyFiltered: 'Sin cobros',
    emptyFilteredMessage: 'Ningún cobro coincide con los filtros',
    emptyInitialMessage: 'Aún no hay cobros registrados',
    viewHistory: 'Ver historial completo',
    historySectionTitle: 'Historial de cobros',
  },

  pay: {
    screenTitle: 'Registrar pago',
    chargeHeader: 'Cobro',
    fieldPaymentMethod: 'Método de pago',
    fieldPaymentDate: 'Fecha de pago',
    fieldNote: 'Nota',
    placeholderNote: 'Ej: Confirmado por WhatsApp',
    confirmButton: 'Confirmar pago',
    errorMethodRequired: 'Seleccioná el método de pago.',
  },

  templates: {
    tab: 'Plantillas',
    screenTitle: 'Plantillas',
    newTitle: 'Nueva plantilla',
    editTitle: 'Editar plantilla',
    deleteAlertTitle: 'Eliminar plantilla',
    deleteAlertMessage: (concept: string) =>
      `¿Eliminar "${concept}"? Los cobros existentes no se verán afectados.`,
    emptyTitle: 'Sin plantillas',
    emptyHint: 'Usa el botón + para agregar una',
    fieldConcept: 'Concepto',
    fieldAmount: 'Monto (₡)',
    placeholderConcept: 'Ej: Mensualidad mayo',
    placeholderAmount: 'Ej: 35000',
    errorConceptRequired: 'El concepto es obligatorio.',
    errorAmountInvalid: 'El monto debe ser un número mayor a 0.',
    fieldType: 'Tipo',
    typeRecurring: 'Recurrente',
    typeExtra: 'Extra',
    pickerTitle: 'Elegir plantilla',
    pickerEmpty: 'No hay plantillas. Crea una desde la pestaña Plantillas.',
  },

  settings: {
    tab: 'Ajustes',
    screenTitle: 'Ajustes',
  },

  importExport: {
    tab: 'Archivos',
    screenTitle: 'Importar / Exportar',
    importTitle: 'Importar desde Excel',
    importHint: 'Seleccioná un archivo .xlsx con hoja "contacts" y/o "templates". Los registros existentes no se duplican.',
    pickFileButton: 'Seleccionar archivo .xlsx',
    importButton: 'Importar',
    warningsTitle: 'Filas omitidas',
    previewContacts: 'Contactos',
    previewTemplates: 'Plantillas',
    templateTitle: 'Plantilla de importación',
    templateHint: 'Descargá el archivo de ejemplo con las columnas correctas para llenar y luego importar.',
    templateButton: 'Descargar plantilla .xlsx',
    exportTitle: 'Exportar historial',
    exportHint: 'Genera un archivo Excel con todas las líneas de cobro registradas.',
    exportButton: 'Exportar historial',
  },

  dashboard: {
    tab: 'Tablero',
    summaryTitle: 'Resumen',
    filterAll: 'Todos',
    filterContact: 'Contacto',
    rangePrevMonth: 'Mes ant.',
    rangeThisMonth: 'Este mes',
    rangeNextMonth: 'Próx. mes',
    allContacts: 'Todos los contactos',
    searchContact: 'Buscar contacto…',
    filterModalTitle: 'Filtrar por contacto',
    totalReceivable: 'Por cobrar',
  },
} as const;
